---
- name: Configure Web Server and Firewall
  hosts: combined_web_firewall
  become: yes
  tasks:
    - name: Install and configure UFW
      apt: name=ufw state=present
    - name: Allow SSH and HTTP/HTTPS through UFW
      ufw:
        rule: allow
        port: "{{ item }}"
      loop: [22, 80, 443]

    - name: Install Docker
      apt: name=docker.io state=latest

    - name: Run Nginx container
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        ports:
          - "80:80"
          - "443:443"
