---
- name: Basic Firewall Setup on VMs
  hosts: all
  become: true
  tasks:
    - name: Ensure UFW is installed (Uncomplicated Firewall)
      apt:
        name: ufw
        state: present

    - name: Allow SSH through the firewall
      ufw:
        rule: allow
        name: OpenSSH

    # Add more rules as per your network security plan
