---
- name: Configure Database Server
  hosts: database_server
  become: yes
  tasks:
    - name: Install MySQL
      apt: name=mysql-server state=latest

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    # Configure database and user (example)
    - name: Ensure the database is present
      mysql_db:
        name: mydatabase
        state: present

    - name: Ensure user has access to the database
      mysql_user:
        name: myuser
        password: mypassword
        priv: '*.*:ALL,GRANT'
        state: present
