---
- name: Network Configuration for VMs
  hosts: all
  become: true
  tasks:
    - name: Install net-tools for network management
      apt:
        name: net-tools
        state: present

    # Additional tasks for configuring network (e.g., setting up interfaces)
