---
- name: Configure Network Settings
  hosts: all
  become: true
  tasks:
    - name: Assign static IP
      community.general.nmcli:
        conn_name: 'eth0'
        ifname: 'eth0'
        type: 'ethernet'
        ip4: '192.168.56.101/24'
        gw4: '192.168.56.1'
        state: 'present'
