---
- name: Install Zabbix with Nginx and PHP-FPM
  hosts: your_host_group
  become: true
  vars:
    db_name: zabbix
    db_user: zabbix
    db_password: zabbix_pass  # Change this to your actual Zabbix DB password
    php_timezone: "America/New_York"

  tasks:
    - name: Add Zabbix official repository
      apt_repository:
        repo: "deb http://repo.zabbix.com/zabbix/6.4/ubuntu/ {{ ansible_distribution_release }} main"
        state: present

    - name: Install Zabbix server, frontend, and agent packages
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-nginx-conf
          - zabbix-agent
        state: present
        update_cache: yes

    - name: Install Nginx and PHP-FPM packages
      apt:
        pkg:
          - nginx
          - php8.1-fpm
          - php8.1-mysql
          - php8.1-mbstring
          - php8.1-gd
          - php8.1-xml
          - php8.1-bcmath
          - php8.1-json
        update_cache: yes
        state: present

    - name: Configure PHP-FPM
      ini_file:
        path: "/etc/php/8.1/fpm/php.ini"
        section: PHP
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { option: 'date.timezone', value: '{{ php_timezone }}' }
        - { option: 'max_execution_time', value: '300' }
        - { option: 'memory_limit', value: '256M' }
        - { option: 'post_max_size', value: '16M' }
        - { option: 'upload_max_filesize', value: '2M' }
      notify:
        - restart php-fpm

    - name: Copy Zabbix Nginx server block configuration
      copy:
        src: zabbix_nginx.conf
        dest: "/etc/nginx/sites-available/zabbix"
        mode: 0644
      notify:
        - reload nginx

    - name: Enable Zabbix Nginx configuration
      file:
        src: "/etc/nginx/sites-available/zabbix"
        dest: "/etc/nginx/sites-enabled/zabbix"
        state: link

    - name: Ensure services are started and enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - nginx
        - php8.1-fpm
        - zabbix-server
        - zabbix-agent

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded

    - name: restart php-fpm
      service:
        name: php8.1-fpm
        state: restarted
